config/routes.rb
Rails.application.routes.draw do
  root 'offers#index'
  devise_for :users
  resources :users, :except => [:edit]
  resources :measures
  resources :locations
  resources :products
  resources :offers do 
    get :reset_filterrific, on: :collection
    collection do
      match 'search' => 'offers#search', via: [:get, :post], as: :search
    end
  end
  
  post "offers/create_offer_user", to: "offers#create_offer_user", as: "create_offer_user"
  post "offers/change_status" => "offers#change_status"
end

app/models/offer.rb
class Offer < ActiveRecord::Base
	# Validations
	validates :service_start_date, presence: true 
	validates :service_finish_date, presence: true 
	validates :offer_start_date, presence: true 
	validates :offer_finish_date, presence: true
	# relationship
	has_many :users, :through => :offer_users
	has_many :offer_users, :dependent => :destroy 
	
	# default for will_paginate
  	self.per_page = 10

	# search dates

	ransacker :service_start_date do
  	Arel::Nodes::SqlLiteral.new("date(offers.service_start_date)")
	end

	ransacker :service_finish_date do
  	Arel::Nodes::SqlLiteral.new("date(offers.service_finish_date)")
	end

	ransacker :offer_finish_date do
  	Arel::Nodes::SqlLiteral.new("date(offers.offer_finish_date)")
	end

	ransacker :offer_start_date do
  	Arel::Nodes::SqlLiteral.new("date(offers.offer_start_date)")
	end

  def self.to_csv(options = {})
    CSV.generate(options) do |csv|
      csv << column_names
      all.each do |offer|
        csv << offer.attributes.values_at(*column_names)
      end
    end
  end
end

app/controllers/offers_controller.rb
class OffersController < ApplicationController
  before_filter :authenticate_user!
  before_action :set_offer, only: [:show, :edit, :update, :destroy]

  # GET /Offers
  # GET /Offers.json
  def index
    @offer = Offer.new()
      @product = Product.new()
      @location = Location.new()
    if current_user.kind == "admin"
      @search = Offer.ransack(params[:q])
      @offers = @search.result.page(params[:page])
      respond_to do |format|
        format.html
        format.js
        format.csv { send_data @offers.to_csv }
        format.xls { send_data @offers.to_csv(col_sep: "\t") }
      end
    else
      @search = Offer.ransack(params[:q])
      @offers = Offer.where(:status => 1).page(params[:page])
      respond_to do |format|
        format.html
        format.js
        format.csv { send_data @offers.to_csv }
        format.xls { send_data @offers.to_csv(col_sep: "\t") }
      end

    end
  end
  
  # GET /Offers/1
  # GET /Offers/1.json
  def show
    @offer_users = OfferUser.where(offer_id: params[:id])
    @offer_user = OfferUser.new()
    if OfferUser.find_by_offer_id_and_user_id(params[:id], current_user)
      @offer_user_find_by_id = OfferUser.find_by_offer_id_and_user_id(params[:id], current_user).status
    else
      @offer_user_find_by_id = false
    end
    
  end

  # GET /Offers/new
  def new
    @offer = Offer.new
  end

  # GET /Offers/1/edit
  def edit
  end

  # POST /Offers
  # POST /Offers.json
  def create
    @offer = Offer.new(offer_params)

    respond_to do |format|
      if @offer.save
        flash[:notice] = 'Se ha creado una oferta'
        format.html { redirect_to @offer}
        format.json { render :show, status: :created, location: @offer }
        format.js   {}
      else
        format.html { render :new }
        format.json { render json: @offer.errors, status: :unprocessable_entity }
        format.js   {}
      end
    end
  end

  
  # POST /Offer_User
  # POST /Offer_User.json
  def create_offer_user
    @offer_user = OfferUser.new(quantity: params[:offer_user][:quantity], price: params[:offer_user][:price], offer_id: params[:offer_user][:offer_id], user_id: params[:offer_user][:user_id])
    respond_to do |format|
      if @offer_user.save
        flash[:notice] = 'Se ha creado una  solicitud de oferta'
        format.html { redirect_to root_path}
        format.js   {}
      else
        format.html { render :new }
        format.json { render json: @offer.errors, status: :unprocessable_entity }
        format.js   {}
      end
    end
  end

  def change_status 
    @offer = Offer.find(params[:id]) 
    val = @offer.status == 1 ? 2 : 1 
    @offer.update_attribute(:status, val)  
    respond_to do |format|
      if @offer.status == 1
        format.html { redirect_to @offer, notice: 'Se ha Activado su oferta' }
      else @offer.status == 2
        format.html { redirect_to @offer, notice: 'Se ha Desactivado su oferta' }
      end
    end    
  end

  def extend
    @offer = Offer.find(params[:id]) 
    @offer.update(params[:date])  
    respond_to do |format|
      format.html { render :show }
    end    
  end


  # PATCH/PUT /Offers/1
  # PATCH/PUT /Offers/1.json
  def update
    respond_to do |format|
      if @offer.update(offer_params)
        flash[:notice] = 'La Oferta ha sido modificada'
        format.html { redirect_to @offer }
        format.json { render :show, status: :ok, location: @offer }
        format.js   { js_redirect_to(offer_path @offer)}
      else
        format.html { render :edit }
        format.js   {}
        format.json { render json: @offer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /Offers/1
  # DELETE /Offers/1.json
  def destroy
    @offer.destroy
    respond_to do |format|
      flash[:notice] = 'Se ha eliminado exitosamente'
      format.html { redirect_to offers_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_offer
      @offer = Offer.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def offer_user_params
      params.require(:offer_user).permit(:destination, :product, :observations,:volumen, :service_start_date, :service_finish_date, :offer_start_date, :offer_finish_date, :liquid_load, :container, :general_load, :load_compensation, :kind, :unit, :price ,:origins)
    end

    def offer_params
      params.require(:offer).permit(:destination, :product, :observations,:volumen, :service_start_date, :service_finish_date, :offer_start_date, :offer_finish_date, :liquid_load, :container, :general_load, :load_compensation, :kind, :unit, :price ,:origins)
    end
  end

app/views/offers/_extend.html.erb
<!-- Modal -->
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button aria-label="Close" data-dismiss="modal" class="close" type="button"><span aria-hidden="true">×</span></button>
        <h4 id="myModalLabel" class="modal-title">Extender el tiempo</h4>
      </div>

      <div class="modal-body">
        <div class="errors">
        </div>
        <form method="post" data-remote="true" accept-charset="UTF-8" action="/products" id="new_product" class="new_product"><input type="hidden" value="✓" name="utf8">
          <label for="product_Referencia">Fecha de Servicio de oferta</label>
          <input type="text" id="product_ref" name="product[ref]" class=" date form-control">
          <label for="product_Nombre">Fecha de oferta</label>
          <input type="text" id="product_name" name="product[name]" class=" date form-control">
          <br>
          <input type="submit" class="btn btn-info btn-block" value="Aegregar" name="commit">
        </form>      
      </div>
    </div>
  </div>
</div>

app/views/offers/_filters.html.erb
<div id="filter-panel" class="collapse filter-panel">
    <div class="panel panel-default">
        <div class="panel-body">
            <%= search_form_for @search do |f| %>
                <div class="col-md-3">
                    <label><%= t('.type')%></label>
                    <%= f.select :kind_cont, [["Tipo Oferta 1", "oferta1"],["Tipo Oferta 2", "oferta2"]], {prompt: "Seleccione Tipo Oferta"}, {class: "form-control"}%>
                </div>
                <div class="col-md-3">
                    <label><%= t('.product')%></label>
                    <%= f.search_field(:product_cont, class: 'filterrific-periodically-observed') %>
                </div>
                <div class="col-md-3">
                    <label><%= t('.origins')%></label>
                    <%= f.search_field(:origins_cont, class: 'filterrific-periodically-observed') %>
                </div>
                <div class="col-md-3">
                    <label><%= t('.destination')%></label>
                    <%= f.search_field(:destination_cont,class: 'filterrific-periodically-observed') %>
                </div>
                 
                <div class="col-md-3">
                    <label><%= t('.service_start_date')%></label>
                    <%= f.search_field(:service_start_date_eq, class: 'date filterrific-periodically-observed') %>
                </div>
                <div class="col-md-3">
                    <label><%= t('.service_finish_date')%></label>
                    <%= f.search_field(:service_finish_date_eq, class: 'date filterrific-periodically-observed') %>
                </div>
                <div class="col-md-3">
                    <label><%= t('.offer_start_date')%></label>
                    <%= f.search_field(:offer_start_date_eq,class: 'date filterrific-periodically-observed') %>
                </div>
                 <div class="col-md-3">
                    <label><%= t('.offer_finish_date')%></label>
                    <%= f.search_field(:offer_finish_date_eq,class: 'date filterrific-periodically-observed') %>
                </div>

                <div class="col-md-3">
                    <br>
                    <%=f.submit :class =>"btn btn-info btn-block" %>
                </div>
                <div class="col-md-3">
                    <br>
                    <%= link_to "Limpiar Filtros", request.path, class:"btn btn-danger btn_white btn-block" %>
                </div>
            <% end %>
        </div>
    </div>
</div>    

<button type="button" class="btn btn-primary" data-toggle="collapse" data-target="#filter-panel"  style="margin-bottom: 10px;">
  <span class="glyphicon glyphicon-filter"></span> <%= t('.filters')%> 
</button>

app/views/offers/_form.html.erb
<div>
  <%= form_for(@offer, remote: true) do |f| %>
  <div class="form-group">
    <label>Tipo de Oferta</label>
    <%= f.select :kind, [["Tipo Oferta 1", "oferta1"],["Tipo Oferta 2", "oferta2"]], {prompt: "Seleccione Tipo Oferta"}, {class: "form-control"}%>
  </div>
  <div class="form-group">
    <label>Carga Compensatoría</label>
    <%= f.check_box :load_compensation%>
  </div>
  <div class="row">
    <div class="col-xs-4 col-sm-4 col-md-4">
      <div class="form-group">
        <label>Tipo de Producto</label>
        <%=  f.collection_select :product, Product.all, :name, :name, {prompt: " "}, {class: "form-control"}%>
      </div>
    </div>
    <div class="col-xs-4 col-sm-4 col-md-4">
      <div class="form-group">
        <label>Origen</label>
        <%=  f.collection_select :origins, Location.all, :location, :location, {prompt: " "}, {class: "form-control"}%>
      </div>
    </div>
    <div class="col-xs-4 col-sm-4 col-md-4">
      <div class="form-group">
        <label>Destino</label>
        <%=  f.collection_select :destination, Location.all, :location, :location, {prompt: " "}, {class: "form-control"}%>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-xs-6 col-sm-6 col-md-6">
      <div class="form-group">
        <label>Und. Cotización</label>
        <%=  f.collection_select :unit, Measure.all, :unit, :unit, {prompt: " "}, {class: "form-control"}%>
      </div>
    </div>
    <div class="col-xs-6 col-sm-6 col-md-6">
      <div class="form-group">
        <label>Volumen Demandado</label>
        <%= f.text_field :volumen, class:"form-control"%>
      </div>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :price, :id => "price"%>
    <%= f.text_field :price, class:"form-control"%>
  </div>

  <div class="row">
    <div class="col-xs-6 col-sm-6 col-md-6">
      <div class="form-group">
        <label>Fecha Inicio Servicio</label>
        <%= f.text_field :service_start_date,class:"form-control date"%>
      </div>
    </div>
    <div class="col-xs-6 col-sm-6 col-md-6">
      <div class="form-group">
        <label>Fecha Fin Servicio </label>
        <%= f.text_field :service_finish_date, class:"form-control date"%>
      </div>
    </div>
  </div>

  <div class="row">
    <div class="col-xs-6 col-sm-6 col-md-6">
      <div class="form-group">
        <label>Fecha Inicio Oferta </label>
        <%= f.text_field :offer_start_date, class:"form-control date"%>
      </div>
    </div>
    <div class="col-xs-6 col-sm-6 col-md-6">
      <div class="form-group">
        <label>Fecha Fin Oferta </label>
        <%= f.text_field :offer_finish_date, class:"form-control date"%>
      </div>
    </div>
  </div>

  <div class="row">
    <div class="col-xs-4 col-sm-4 col-md-4">
      <div class="form-group">
        <label>Contenedor</label>
        <%= f.check_box :container, :class=>"group_checked"%>
      </div>
    </div>
    <div class="col-xs-4 col-sm-4 col-md-4">
      <div class="form-group">
        <label>Carga General</label>
        <%= f.check_box :general_load, :class=>"group_checked"%>
      </div>
    </div>
    <div class="col-xs-4 col-sm-4 col-md-4">
      <div class="form-group">
        <label>Carga Liquida</label>
        <%= f.check_box :liquid_load, :class=>"group_checked"%>
      </div>
    </div>
  </div>

  <div class="form-group">
    <label>Observaciones</label>
    <br>
    <%= f.text_area :observations, :rows => "4" , :cols => "2" , :class => "textare_w100"%>
  </div>
  <%= f.submit :class =>"btn btn-info btn-block"%>
  <%end%>
</div>

app/views/offers/_list.html.slim
#filterrific_results
  table.table.table-striped.table-hover.table-bordered
    thead
    tr
      th 
        =  sort_link @search, :product, t('.product')
      th 
        = sort_link @search, :origins, t('.origins')
      th 
        = sort_link @search, :destination, t('.destination')
      th 
        = sort_link @search, :volumen,t('.volumen')
      th 
        = sort_link @search, :price,t('.price')
      th 
        = sort_link @search, :service_start_date, t('.service_start_date')
      th 
        = sort_link @search, :service_finish_date, t('.service_finish_date')
      th 
        = sort_link @search, :offer_start_date, t('.offer_start_date')
      th 
        = sort_link @search, :offer_finish_date, t('.offer_finish_date')
      - if current_user.kind == "admin"
        th
        th
        th
    
    - @offers.each do |offer| 
      tr class=('danger' if offer.status == 2)
        td
          - if current_user.kind == "admin"
            span.badge.progress-bar-success
              = user_count(offer)
          = link_to(offer.product, offer_path(offer.id), :data => {:date => offer.offer_finish_date}, :class => "offer_id",:id => 'my-link')
        td
          = offer.origins
        td
          = offer.destination
        td.w90
          = "#{offer.volumen} #{offer.unit}"
        td.w90
          = number_to_currency_br(offer.price)
        td
          = offer.service_start_date.strftime("%d-%m-%Y")
        td
          = offer.service_finish_date.strftime("%d-%m-%Y")
        td
          = offer.offer_start_date.strftime("%d-%m-%Y")
        td
          = offer.offer_finish_date.strftime("%d-%m-%Y")
        - if current_user.kind == "admin"
          td
            = link_to edit_offer_path(offer)
                span.glyphicon.glyphicon-pencil
          td
            = link_to offer, data: {:confirm => t('.delete')}, :method => :delete do
              span.glyphicon.glyphicon-trash
          td
            button.btn.btn-link data-toggle="modal" data-target="#myModal#{offer.id}" 
                span.glyphicon.glyphicon-eye-open
            = render(partial: 'offers/modal',locals: { offer: offer })
  = will_paginate @offers, :locals => { :offers => @offers }, renderer: BootstrapPagination::Rails

app/views/offers/_modal.html.erb
<!-- Modal -->
<div class="modal fade" id="myModal<%= offer.id%>" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModal<%= offer.id %>-label"><%= t('.observations')%></h4>
      </div>
      <div class="modal-body">
        <%= offer.observations%>
      </div>
    </div>
  </div>
</div>

app/views/offers/_modal_offer.html.erb
<!-- Modal -->
<div class="modal fade" id="myModalOferta" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel"><%= t('.add_offer')%></h4>
      </div>
      <div class="modal-body">
        <div class="errors"></div>
        <%= render 'form'%>
      </div>
      
    </div>
  </div>
</div>

app/views/offers/_provider_form.html.erb
<div class="col-md-12">
	<div class="panel panel-default">
		<div class="panel-heading">
			<h3>¿ Desea inscribirse en esta oferta ? </h3>
		</div>
		<div class="panel-body">
      <div class="row">
        <div class="col-xs-6">
          <div class="well">
            <%= form_for :offer_user, url: url_for( :controller => :offers, :action => :create_offer_user ), html: { method: :post } do |f| %>
              
              <%= f.label :Cantidad%>
              <%= f.number_field :quantity, :class =>"form-control", :max => "#{@offer.volumen}"%>
              <%= f.label :Precio%>
              <%= f.text_field :price, :class =>"form-control"%>
              <%= f.hidden_field :offer_id, :value => "#{params[:id]}" %>
              <%= f.hidden_field :user_id, :value => "#{current_user.id}" %>
              <br>
              <%= f.submit :class =>"btn btn-info btn-block",disabled: @offer_user_find_by_id%>
            <%end%>
          </div>
        </div>
        <div class="col-xs-6">
          <p class="lead">Recuerda para inscribirte :</p>
          <ul class="list-unstyled" style="line-height: 2">
            <li><span class="fa fa-check text-success"></span> See all your orders</li>
            <li><span class="fa fa-check text-success"></span> Fast re-order</li>
            <li><span class="fa fa-check text-success"></span> Save your favorites</li>
            <li><span class="fa fa-check text-success"></span> Fast checkout</li>
          </ul>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/offers/_providers.html.erb
<div class="row">
		<div class="col-md-12">
			<div class="panel panel-primary">
				<div class="panel-heading">
					<h3 class="panel-title">Ranking Proveedores</h3>
				</div>
				<table class="table table-hover" id="dev-table">
					<thead>
						<tr>
							<th>#</th>
							<th>Nombre</th>
							<th>Transportista</th>
							<th>Cantidad a transportar</th>
							<th>Precio</th>
							<th>Telefono Fijo</th>
							<th>Telefono Celular</th>
						</tr>
					</thead>
					<tbody>
						<%@offer_users.each do |offer_user|%>
							<tr>
								<td><%= offer_user.id%></td>
								<td><%= offer_user.user.name %></td>
								<td><%= offer_user.user.carrier %></td>
								<td><%= offer_user.quantity %></td>
								<td><%= offer_user.price %></td>
								<td><%= offer_user.user.landline %></td>
								<td><%= offer_user.user.cell_phone %></td>
							</tr>
						<%end%>
					</tbody>
				</table>
			</div>
		</div>
	</div>

app/views/offers/_shortcuts.html.erb
<div class="row">
	<div class="col-lg-3 col-md-6">
		<div class="panel panel-primary">
			<div class="panel-heading">
				<div class="row">
					<div class="col-xs-3">
						<i class="fa fa-users"></i>
					</div>
					<div class="col-xs-9 text-right">
						<div class="huge"><%= User.all.count%></div>
						<div><%= t('.provider')%></div>
					</div>
				</div>
			</div>
			<a href="#">
				<div class="panel-footer">
					<i class="pull-left"><a href="#" data-toggle="modal" data-target="#myModalProveedore"><%= t('.add_provider')%></a></i>
					<span class="pull-right"><i class="fa fa-arrow-circle-right"></i></span>
					<div class="clearfix"></div>
				</div>
			</a>
		</div>
	</div>
	<div class="col-lg-3 col-md-6">
		<div class="panel panel-primary">
			<div class="panel-heading">
				<div class="row">
					<div class="col-xs-3">
						<i class="fa fa-truck"></i>
					</div>
					<div class="col-xs-9 text-right">
						<div class="huge"><%= Offer.all.count%></div>
						<div><%= t('.offers')%></div>
					</div>
				</div>
			</div>
			<a href="#">
				<div class="panel-footer">
					<i class="pull-left"><a href="#" data-toggle="modal" data-target="#myModalOferta"><%= t('.add_offer')%></a></i>
					<span class="pull-right"><i class="fa fa-arrow-circle-right"></i></span>
					<div class="clearfix"></div>
				</div>
			</a>
		</div>
	</div>
	<div class="col-lg-3 col-md-6">
		<div class="panel panel-primary">
			<div class="panel-heading">
				<div class="row">
					<div class="col-xs-3">
						<i class="fa fa-bookmark"></i>
					</div>
					<div class="col-xs-9 text-right">
						<div class="huge"><%= Product.all.count%></div>
						<div><%= t('.products')%></div>
					</div>
				</div>
			</div>
			<a href="#">
				<div class="panel-footer">
					<i class="pull-left"><a href="#" data-toggle="modal" data-target="#myModalProducto"><%= t('.add_product')%></a></i>
					<span class="pull-right"><i class="fa fa-arrow-circle-right"></i></span>
					<div class="clearfix"></div>
				</div>
			</a>
		</div>
	</div>
	<div class="col-lg-3 col-md-6">
		<div class="panel panel-primary">
			<div class="panel-heading">
				<div class="row">
					<div class="col-xs-3">
						<i class="fa fa-location-arrow"></i>
					</div>
					<div class="col-xs-9 text-right">
						<div class="huge"><%= Location.all.count%></div>
						<div><%= t('.locations')%></div>
					</div>
				</div>
			</div>
			<a href="#">
				<div class="panel-footer">
					<i class="pull-left"><a href="#" data-toggle="modal" data-target="#myModalLocation"><%= t('.add_location')%></a></i>
					<span class="pull-right"><i class="fa fa-arrow-circle-right"></i></span>
					<div class="clearfix"></div>
				</div>
			</a>
		</div>
	</div>
	
</div>

<%= render(partial: 'users/modal')%>
<%= render(partial: 'products/modal')%>
<%= render(partial: 'offers/modal_offer')%>
<%= render(partial: 'locations/modal')%>

app/views/offers/edit.html.erb
<div class="page-header">
	<ol class="breadcrumb">
		<li class="active">
			<i class="fa fa-truck"></i> 
			Editar Oferta
		</li>
	</ol>
</div>
<div class="row">
	<div class="col-md-12">
		<div class="panel panel-default">
			<div class="panel-heading">
				<h3><strong><%= t('.offer')%> <%= @offer.kind%> No.<%= @offer.id%></strong> </h3>
			</div>
			<div class="panel-body">
				<div class="row">
					<div class="col-lg-12">
						<%= render 'offers/form' , offer: @offer%>
					</div>
     			</div>
			</div>
		</div>
	</div>
</div>

app/views/offers/index.js.erb
<% js = escape_javascript(render(partial: 'offers/list', locals: { offers: @offers })) %>
$("#filterrific_results").html("<%= js %>");

app/views/offers/show.html.erb
<div class="page-header">
	<ol class="breadcrumb">
		<li class="active">
			<i class="fa fa-truck"></i> 
			<%= t('.head')%>
		</li>
	</ol>
</div>

<div class="row">
	<div class="col-xs-12">
		<div class="countdown">
		</div>
		<br>
		<br>
	</div>
</div>

<div class="row">
	<div class="col-md-12">
		<div class="panel panel-default">
			<div class="panel-heading">
				<h3><strong><%= t('.offer')%> <%= @offer.kind%> No.<%= @offer.id%></strong> </h3>
			</div>
			<div class="panel-body">
				<%if current_user.kind == "admin"%>
					<div class="row">
						<div class="col-lg-3">
							<p><a href="#" class="btn btn-outlined btn-block btn-success" data-toggle="modal" data-target="#myModal"><%= t('.extend')%></a></p>
						</div>
						<div class="col-lg-3">
							<p><%= link_to(t('.edit'), edit_offer_path(@offer), html_options = {:class => "btn btn-outlined btn-block btn-info"})%></p> 
						</div>
						<div class="col-lg-3">
							<%= button_to statuts(@offer.status), { :controller => "offers", :action => "change_status", :id => @offer.id, :method => :put}, html_options = {:class => "btn btn-outlined btn-block  btn_white btn-warning"} %>
						</div>
						<div class="col-lg-3">
							<p><%= link_to(t('.delete'), @offer, html_options = {:class => "btn btn_white btn-outlined btn-block btn-danger", data: {:confirm => t('.data_delete')}, :method => :delete} )%></p> 
						</div>
					</div>
					<hr>
				<%end%>
				
				<div class="row">
					<div class="row">
						<div class="col-lg-12">
							<div class="col-lg-6">
								<span class="bold"> <%= t('.product')%></span>
								<p><%= @offer.product%></p>
							</div>
							<div class="col-lg-6">
								<span class="bold"><%= t('.volumen')%></span>
								<p><%= @offer.volumen%> <%= @offer.unit%></p>
							</div>
						</div>
						<div class="col-lg-12">
							<div class="col-lg-6">
								<span class="bold"><%= t('.origins')%></span>
								<p><%= @offer.origins%></p>
							</div>
							<div class="col-lg-6">
								<span class="bold"><%= t('.destination')%></span>
								<p><%= @offer.destination%></p>
							</div>
						</div>
						<div class="col-lg-12">
							<div class="col-lg-4">
								<span class="bold"><%= t('.liquid_load')%></span>
								<p><%= boolean_translate(@offer.liquid_load)  %></p>
							</div>
							<div class="col-lg-4">
								<span class="bold"><%= t('.general_load')%></span>
								<p><%=boolean_translate(@offer.general_load)%></p>
							</div>
							<div class="col-lg-4">
								<span class="bold"><%= t('.container')%></span>
								<p><%= boolean_translate(@offer.container)%></p>
							</div>
							<br>
						</div>
							
						<div class="col-lg-12">
							<hr>
							<div class="col-lg-6">
								<span class="bold"><%= t('.offer_start_date')%></span>
								<p><%= @offer.offer_start_date%></p>
							</div>
							<div class="col-lg-6">
								<span class="bold"><%= t('.offer_finish_date')%></span>
								<p><%= @offer.offer_finish_date%></p>
							</div>
						</div>
					<%if current_user.kind == "admin"%>
						<div class="col-lg-12">
							<div class="col-lg-6">
								<span class="bold"><%= t('.service_start_date')%></span>
								<p><%= @offer.service_start_date%></p>
							</div>
							<div class="col-lg-6">
								<span class="bold"><%= t('.service_finish_date')%></span>
								<p><%= @offer.service_finish_date%></p>
							</div>
						</div>
					</div>
					
						<div class="col-lg-12">
							<hr>	
							<span class="bold"><%= t('.observations')%></span>
							<p><%= @offer.observations%></p>
						</div>
					<%end%>
				</div>
			</div>
		</div>
	</div>
</div>
<%if current_user.kind == "admin"%>
	<%= render(partial: 'offers/providers') %>
<%else%>
	<%= render(partial: 'offers/provider_form') %>
<%end%>
<%= render(partial: 'offers/extend') %>