config/routes.rb
Rails.application.routes.draw do
  root 'offers#index'
  devise_for :users
  resources :users, :except => [:edit]
  resources :measures
  resources :locations
  resources :products
  resources :offers do 
    get :reset_filterrific, on: :collection
    collection do
      match 'search' => 'offers#search', via: [:get, :post], as: :search
    end
  end
  
  post "offers/create_offer_user", to: "offers#create_offer_user", as: "create_offer_user"
  post "offers/change_status" => "offers#change_status"
end

app/models/product.rb
class Product < ActiveRecord::Base
	# Validations
	validates :name, presence: true 
	validates :ref, presence: true 

	self.per_page = 10

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  helper_method :sort_column, :sort_direction
  before_filter :authenticate_user!
  before_action :set_product, only: [:show, :edit, :update, :destroy]
  
  def index
    @search = Product.ransack(params[:q])
    @products = @search.result.page(params[:page])
    @product = Product.new
    respond_to do |format|
      format.html
      format.js
    end
  end
  
  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        flash[:notice] = 'El producto ha sido creado'
        format.html { redirect_to @product }
        format.js   {}
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.js   {}
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /Offers/1
  # PATCH/PUT /Offers/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        flash[:notice] = 'La producto ha sido actualizado'
        format.html { redirect_to @product }
        format.json { render :show, status: :ok, location: @product }
        format.js   { js_redirect_to(products_path)}
      else
        format.html { render :edit }
        format.js   {}
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end
  
  def destroy
    @product = Product.find(params[:id])
    @product.destroy
    flash[:notice] = 'El producto ha sido eliminado'
    redirect_to products_url
  end
  
  private

  # Use callbacks to share common setup or constraints between actions.
  def set_product
    @product = Product.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def product_params
    params.require(:product).permit(:ref, :name, :details)
  end
  
  def sort_column
    Product.column_names.include?(params[:sort]) ? params[:sort] : "name"
  end
  
  def sort_direction
    %w[asc desc].include?(params[:direction]) ? params[:direction] : "asc"
  end
end

app/views/products/_filters.html.erb
<div id="filter-panel" class="collapse filter-panel">
    <div class="panel panel-default">
        <div class="panel-body">
            <%= search_form_for @search do |f| %>
                <div class="col-md-3">
                    <label><%= t('.name')%></label>
                    <%= f.search_field(:name_cont, class: 'filterrific-periodically-observed') %>
                </div>
                <div class="col-md-3">
                    <label><%= t('.ref')%></label>
                    <%= f.search_field(:ref_cont, class: 'filterrific-periodically-observed') %>
                </div>
                <div class="col-md-3">
                    <br>
                    <%=f.submit :class =>"btn btn-info btn-block" %>
                </div>
                <div class="col-md-3">
                    <br>
                    <%= link_to t('.clear'), request.path, class:"btn btn-danger btn_white btn-block" %>
                </div>
            <% end %>
        </div>
    </div>
</div>    

<button type="button" class="btn btn-primary" data-toggle="collapse" data-target="#filter-panel"  style="margin-bottom: 10px;">
  <span class="glyphicon glyphicon-filter"></span> <%= t('.filters')%> 
</button>
<button type="button" class="btn btn-primary" data-toggle="modal" data-target="#myModalProducto"  style="margin-bottom: 10px;">
    <span class="fa fa-plus"></span> <%= t('.add')%>
</button>
<%= render(partial: 'products/modal')%>

app/views/products/_form.html.slim
= form_for @product,  remote: true do |f|
    = f.label :Referencia
    = f.text_field :ref, :class =>"form-control"
    = f.label :Nombre
    = f.text_field :name, :class =>"form-control"
    br
    =f.submit :class =>"btn btn-info btn-block"
       

app/views/products/_list.html.slim
#filterrific_results
  table.table.table-striped.table-hover.table-bordered
    thead
    tr
      th #
      th =  sort_link @search, :name, t('.name')
      th =  sort_link @search, :ref, t('.ref')
      th
      th
      - for product in @products
        tr
          td = product.id
          td = product.name
          td = product.ref
          td
            = link_to edit_product_path(product)
              span.glyphicon.glyphicon-pencil
          td =  link_to product, data: {:confirm => t('.delete')}, :method => :delete do
              span.glyphicon.glyphicon-trash
  = will_paginate @products, :locals => { :products => @products }, renderer: BootstrapPagination::Rails

app/views/products/_modal.html.erb
<!-- Modal -->
<div class="modal fade" id="myModalProducto" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">Agregar Producto</h4>
      </div>
      <div class="modal-body">
        <div class="errors"></div>
        <%= render 'products/form'%>
      </div>
    </div>
  </div>
</div>

app/views/products/create.js.erb
<%if @product.errors.any? %>
	$('.errors').append('<div class="alert alert-danger" role="alert"><button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button> <%= @product.errors.full_messages.to_sentence%></div>');
<%else%>
	$('.errors').append('<div class="alert alert-success" role="alert"><button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button><strong> Se ha creado su nueva producto </strong></div>');
	$('#product_ref').val(" ")
	$('#product_name').val(" ")
<%end%>

app/views/products/edit.html.erb
<div class="page-header">
	<ol class="breadcrumb">
		<li class="active">
			<i class="fa fa-bookmark"></i> 
			Editar Producto
		</li>
	</ol>
</div>
<div class="row">
	<div class="col-md-12">
		<div class="panel panel-default">
			<div class="panel-heading">
				<h3><strong> Producto No.<%= @product.id%></strong> </h3>
			</div>
			<div class="panel-body">
				<div class="row">
					<div class="col-lg-12">
						<%= render 'form'%>
					</div>
     			</div>
			</div>
		</div>
	</div>
</div>

app/views/products/index.html.slim
.page-header
  ol.breadcrumb
    li.active
      i.fa.fa-bookmark
      | LISTADO DE PRODUCTOS

= render(partial: 'products/filters')
= render(partial: 'products/list',locals: { products: @products })

app/views/products/index.js.erb
<% js = escape_javascript(render(partial: 'products/list', locals: { products: @products })) %>
$("#filterrific_results").html("<%= js %>");