config/routes.rb
Rails.application.routes.draw do
  root 'offers#index'
  devise_for :users
  resources :users, :except => [:edit]
  resources :measures
  resources :locations
  resources :products
  resources :offers do 
    get :reset_filterrific, on: :collection
    collection do
      match 'search' => 'offers#search', via: [:get, :post], as: :search
    end
  end
  
  post "offers/create_offer_user", to: "offers#create_offer_user", as: "create_offer_user"
  post "offers/change_status" => "offers#change_status"
end

app/models/measure.rb
class Measure < ActiveRecord::Base
	# Validations
	validates :unit, presence: true 
	
	self.per_page = 10

end

app/controllers/measures_controller.rb
class MeasuresController < ApplicationController
  before_filter :authenticate_user!
  before_action :set_measure, only: [:show, :edit, :update, :destroy]

  # GET /measures
  # GET /measures.json

  def index
    @search = Measure.ransack(params[:q])
    @measures = @search.result.page(params[:page])
    @measure = Measure.new()
    respond_to do |format|
      format.html
      format.js
    end
  end

  # GET /measures/1
  # GET /measures/1.json
  def show
  end

  # GET /measures/new
  def new
    @measure = Measure.new
  end

  # GET /measures/1/edit
  def edit
  end

  # POST /measures
  # POST /measures.json
  def create
    @measure = Measure.new(measure_params)

    respond_to do |format|
      if @measure.save
        flash[:notice] = 'Se ha actualizado Unidad de medidad'
        format.html { redirect_to @measure, notice: 'Measure was successfully created.' }
        format.json { render :show, status: :created, location: @measure }
        format.js   {}
      else
        format.html { render :new }
        format.json { render json: @measure.errors, status: :unprocessable_entity }
        format.js   {}
      end
    end
  end

  # PATCH/PUT /measures/1
  # PATCH/PUT /measures/1.json
  def update
    respond_to do |format|
      if @measure.update(measure_params)
        flash[:notice] = 'Se ha creado Unidad de medidad'
        format.html { redirect_to @measure }
        format.json { render :show, status: :ok, location: @measure }
        format.js   { js_redirect_to(measures_path)}
      else
        format.html { render :edit }
        format.js   {}
        format.json { render json: @measure.errors, status: :unprocessable_entity }
      end
    end
  end
  # DELETE /measures/1
  # DELETE /measures/1.json
  def destroy
    @measure.destroy
    respond_to do |format|
      flash[:notice] = 'Se ha eliminado'
      format.html { redirect_to measures_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_measure
      @measure = Measure.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def measure_params
      params.require(:measure).permit(:unit)
    end

end

app/views/measures/_filters.html.erb
<div id="filter-panel" class="collapse filter-panel">
    <div class="panel panel-default">
        <div class="panel-body">
            <%= search_form_for @search do |f| %>
                <div class="col-md-3">
                    <label><%= t('.unit')%></label>
                    <%= f.search_field(:unit_cont, class: 'filterrific-periodically-observed') %>
                </div>
                <div class="col-md-3">
                    <br>
                    <%=f.submit :class =>"btn btn-info btn-block" %>
                </div>
                <div class="col-md-3">
                    <br>
                    <%= link_to t('.clear'), request.path, class:"btn btn-danger btn_white btn-block" %>
                </div>
            <% end %>
        </div>
    </div>
</div>    

<button type="button" class="btn btn-primary" data-toggle="collapse" data-target="#filter-panel"  style="margin-bottom: 10px;">
  <span class="glyphicon glyphicon-filter"></span> <%= t('.filters')%> 
</button>
<button type="button" class="btn btn-primary" data-toggle="modal" data-target="#myModalmeasure"  style="margin-bottom: 10px;">
    <span class="fa fa-plus"></span> <%= t('.add')%>
</button>
<%= render(partial: 'measures/modal')%>

app/views/measures/_form.html.slim
= form_for @measure,  remote: true do |f|
    = f.label :Unidad_De_Medida
    = f.text_field :unit, :class =>"form-control"
    br
    =f.submit :class =>"btn btn-info btn-block"

app/views/measures/_list.html.slim
#filterrific_results
  table.table.table-striped.table-hover.table-bordered
    thead
    tr
      th #
      th Unidad
      th
      th
      - @measures.each do |measure|
        tr
          th = measure.id
          td = measure.unit
          td
            = link_to edit_measure_path(measure)
              span.glyphicon.glyphicon-pencil
          td =  link_to measure, data: {:confirm => 'Esta seguro que desea elimanar este unidad'}, :method => :delete do
              span.glyphicon.glyphicon-trash
  = will_paginate @measures, :locals => { :measures => @measures }, renderer: BootstrapPagination::Rails

app/views/measures/_modal.html.erb
<!-- Modal -->
<div class="modal fade" id="myModalmeasure" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">Agregar Unidad de medida</h4>
      </div>
      <div class="modal-body">
        <div class="errors"></div>
          <%= render 'measures/form'%>
      </div>
    </div>
  </div>
</div>

app/views/measures/create.js.erb
<%if @measures.errors.any? %>
	$('.errors').append('<div class="alert alert-danger" role="alert"><button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button> <%= @product.errors.full_messages.to_sentence%></div>');
<%else%>
	$('.errors').append('<div class="alert alert-success" role="alert"><button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button><strong> Se ha creado su nueva producto </strong></div>');
	$('#measure_unit').val(" ")
<%end%>

app/views/measures/edit.html.erb
<div class="page-header">
	<ol class="breadcrumb">
		<li class="active">
			<i class="fa fa-calculator"></i> 
			<%= t('.head')%>
		</li>
	</ol>
</div>
<div class="row">
	<div class="col-md-12">
		<div class="panel panel-default">
			<div class="panel-heading">
				<h3><strong> Und. Medida No.<%= @measure.id%></strong> </h3>
			</div>
			<div class="panel-body">
				<div class="row">
					<div class="col-lg-12">
						<%= render 'form'%>
					</div>
     			</div>
			</div>
		</div>
	</div>
</div>

app/views/measures/index.html.slim
.page-header
  ol.breadcrumb
    li.active
      i.fa.fa-calculator style="margin-right: 5px;"
      | LISTADO DE UNIDADES DE MEDIDA

= render(partial: 'measures/filters')
= render(partial: 'measures/list',locals: { measures: @measures })

app/views/measures/show.html.slim
p#notice = notice

p
  strong Unit:
  = @measure.unit

= link_to 'Edit', edit_measure_path(@measure)
'|
= link_to 'Back', measures_path